### ISSUE TITLE
troubles installing Fred2

### ISSUE THREAD

**Issue by UsmanSaeed08** [FRED-2/Fred2#14]
I downloaded the Fred2.zip available here and used the following commands

unzip Fred2-master.zip
cd Fred2-master/
sudo -H python setup.py sdist
cd dist
sudo -H pip install Fred2-2.0.0a1.tar.gz

The following output is produced. The error is given in the end. Same output is produced without the sudo command or the -H flag.
Please let me know any solution as soon as possible. 
I am using Ubuntu latest 14 version

running sdist
running egg_info
creating Fred2.egg-info
writing requirements to Fred2.egg-info/requires.txt
writing Fred2.egg-info/PKG-INFO
writing top-level names to Fred2.egg-info/top_level.txt
writing dependency_links to Fred2.egg-info/dependency_links.txt
writing entry points to Fred2.egg-info/entry_points.txt
writing manifest file 'Fred2.egg-info/SOURCES.txt'
reading manifest file 'Fred2.egg-info/SOURCES.txt'
writing manifest file 'Fred2.egg-info/SOURCES.txt'
running check
creating Fred2-2.0.0a1
creating Fred2-2.0.0a1/Fred2
creating Fred2-2.0.0a1/Fred2.egg-info
creating Fred2-2.0.0a1/Fred2/Apps
creating Fred2-2.0.0a1/Fred2/CleavagePrediction
creating Fred2-2.0.0a1/Fred2/Core
creating Fred2-2.0.0a1/Fred2/Data
creating Fred2-2.0.0a1/Fred2/Data/svms
creating Fred2-2.0.0a1/Fred2/Data/svms/MHCIIMulti
creating Fred2-2.0.0a1/Fred2/Data/svms/MHCIIMulti/models
creating Fred2-2.0.0a1/Fred2/Data/svms/svmhc
creating Fred2-2.0.0a1/Fred2/Data/svms/svmtap
creating Fred2-2.0.0a1/Fred2/Data/svms/unitope
creating Fred2-2.0.0a1/Fred2/Distance2Self
creating Fred2-2.0.0a1/Fred2/EpitopeAssembly
creating Fred2-2.0.0a1/Fred2/EpitopePrediction
creating Fred2-2.0.0a1/Fred2/EpitopeSelection
creating Fred2-2.0.0a1/Fred2/HLAtyping
creating Fred2-2.0.0a1/Fred2/IO
creating Fred2-2.0.0a1/Fred2/TAPPrediction
creating Fred2-2.0.0a1/Fred2/test
making hard links in Fred2-2.0.0a1...
hard linking README.rst -> Fred2-2.0.0a1
hard linking setup.py -> Fred2-2.0.0a1
hard linking Fred2/__init__.py -> Fred2-2.0.0a1/Fred2
hard linking Fred2.egg-info/PKG-INFO -> Fred2-2.0.0a1/Fred2.egg-info
hard linking Fred2.egg-info/SOURCES.txt -> Fred2-2.0.0a1/Fred2.egg-info
hard linking Fred2.egg-info/dependency_links.txt -> Fred2-2.0.0a1/Fred2.egg-info
hard linking Fred2.egg-info/entry_points.txt -> Fred2-2.0.0a1/Fred2.egg-info
hard linking Fred2.egg-info/requires.txt -> Fred2-2.0.0a1/Fred2.egg-info
hard linking Fred2.egg-info/top_level.txt -> Fred2-2.0.0a1/Fred2.egg-info
hard linking Fred2/Apps/EpitopeAssembly.py -> Fred2-2.0.0a1/Fred2/Apps
hard linking Fred2/Apps/EpitopePrediction.py -> Fred2-2.0.0a1/Fred2/Apps
hard linking Fred2/Apps/SNEPv3.py -> Fred2-2.0.0a1/Fred2/Apps
hard linking Fred2/Apps/SpacerDesign.py -> Fred2-2.0.0a1/Fred2/Apps
hard linking Fred2/Apps/__init__.py -> Fred2-2.0.0a1/Fred2/Apps
hard linking Fred2/CleavagePrediction/ANN.py -> Fred2-2.0.0a1/Fred2/CleavagePrediction
hard linking Fred2/CleavagePrediction/PSSM.py -> Fred2-2.0.0a1/Fred2/CleavagePrediction
hard linking Fred2/CleavagePrediction/__init__.py -> Fred2-2.0.0a1/Fred2/CleavagePrediction
hard linking Fred2/Core/Allele.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Base.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Generator.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Peptide.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Protein.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Result.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Transcript.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/Variant.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Core/__init__.py -> Fred2-2.0.0a1/Fred2/Core
hard linking Fred2/Data/CleaveagePSSMMatrices.py -> Fred2-2.0.0a1/Fred2/Data
hard linking Fred2/Data/DistanceMatrices.py -> Fred2-2.0.0a1/Fred2/Data
hard linking Fred2/Data/EpitopePSSMMatrices.py -> Fred2-2.0.0a1/Fred2/Data
hard linking Fred2/Data/TAPPSSMMatrices.py -> Fred2-2.0.0a1/Fred2/Data
hard linking Fred2/Data/UniTope_encodedAlleles.py -> Fred2-2.0.0a1/Fred2/Data
hard linking Fred2/Data/__init__.py -> Fred2-2.0.0a1/Fred2/Data
'Fred2/Data/examples' not a regular file -- skipping
'Fred2/Data/svms' not a regular file -- skipping
'Fred2/Data/tmp' not a regular file -- skipping
hard linking Fred2/Data/svms/__init__.py -> Fred2-2.0.0a1/Fred2/Data/svms
hard linking Fred2/Data/svms/MHCIIMulti/__init__.py -> Fred2-2.0.0a1/Fred2/Data/svms/MHCIIMulti
hard linking Fred2/Data/svms/MHCIIMulti/models/__init__.py -> Fred2-2.0.0a1/Fred2/Data/svms/MHCIIMulti/models
hard linking Fred2/Data/svms/svmhc/__init__.py -> Fred2-2.0.0a1/Fred2/Data/svms/svmhc
hard linking Fred2/Data/svms/svmtap/__init__.py -> Fred2-2.0.0a1/Fred2/Data/svms/svmtap
hard linking Fred2/Data/svms/unitope/__init__.py -> Fred2-2.0.0a1/Fred2/Data/svms/unitope
hard linking Fred2/Distance2Self/Distance2Self.py -> Fred2-2.0.0a1/Fred2/Distance2Self
hard linking Fred2/Distance2Self/DistanceMatrix.py -> Fred2-2.0.0a1/Fred2/Distance2Self
hard linking Fred2/Distance2Self/__init__.py -> Fred2-2.0.0a1/Fred2/Distance2Self
hard linking Fred2/EpitopeAssembly/EpitopeAssembly.py -> Fred2-2.0.0a1/Fred2/EpitopeAssembly
hard linking Fred2/EpitopeAssembly/MosaicVaccine.py -> Fred2-2.0.0a1/Fred2/EpitopeAssembly
hard linking Fred2/EpitopeAssembly/__init__.py -> Fred2-2.0.0a1/Fred2/EpitopeAssembly
hard linking Fred2/EpitopePrediction/External.py -> Fred2-2.0.0a1/Fred2/EpitopePrediction
hard linking Fred2/EpitopePrediction/PSSM.py -> Fred2-2.0.0a1/Fred2/EpitopePrediction
hard linking Fred2/EpitopePrediction/SVM.py -> Fred2-2.0.0a1/Fred2/EpitopePrediction
hard linking Fred2/EpitopePrediction/__init__.py -> Fred2-2.0.0a1/Fred2/EpitopePrediction
hard linking Fred2/EpitopeSelection/OptiTope.py -> Fred2-2.0.0a1/Fred2/EpitopeSelection
hard linking Fred2/EpitopeSelection/__init__.py -> Fred2-2.0.0a1/Fred2/EpitopeSelection
hard linking Fred2/HLAtyping/HLAtyping.py -> Fred2-2.0.0a1/Fred2/HLAtyping
hard linking Fred2/HLAtyping/__init__.py -> Fred2-2.0.0a1/Fred2/HLAtyping
hard linking Fred2/IO/ADBAdapter.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/IO/EnsemblAdapter.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/IO/FileReader.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/IO/MartsAdapter.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/IO/RefSeqAdapter.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/IO/UniProtAdapter.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/IO/__init__.py -> Fred2-2.0.0a1/Fred2/IO
hard linking Fred2/TAPPrediction/PSSM.py -> Fred2-2.0.0a1/Fred2/TAPPrediction
hard linking Fred2/TAPPrediction/SVM.py -> Fred2-2.0.0a1/Fred2/TAPPrediction
hard linking Fred2/TAPPrediction/__init__.py -> Fred2-2.0.0a1/Fred2/TAPPrediction
hard linking Fred2/test/CleavagePredictionTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/DummyAdapter.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/DummyEpitopePredictor.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/EpitopeAssemblyTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/EpitopePredictionTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/OptiTopeTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/ProteinTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/SpacerDesignTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/TAPPredictionTest.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/VariantsForTesting.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/__init__.py -> Fred2-2.0.0a1/Fred2/test
hard linking Fred2/test/test_transcript_generator.py -> Fred2-2.0.0a1/Fred2/test
Writing Fred2-2.0.0a1/setup.cfg
creating dist
Creating tar archive
removing 'Fred2-2.0.0a1' (and everything under it)
xainab@XLaptop:~/Fred2-master$ cd dist/
xainab@XLaptop:~/Fred2-master/dist$ sudo -H pip install Fred2-2.0.0a1.tar.gz 
Unpacking ./Fred2-2.0.0a1.tar.gz
  Running setup.py (path:/tmp/pip-W433WE-build/setup.py) egg_info for package from file:///home/xainab/Fred2-master/dist/Fred2-2.0.0a1.tar.gz
    
Requirement already satisfied (use --upgrade to upgrade): pandas in /usr/local/lib/python2.7/dist-packages (from Fred2==2.0.0a1)
Requirement already satisfied (use --upgrade to upgrade): pyomo>=4.0 in /usr/local/lib/python2.7/dist-packages (from Fred2==2.0.0a1)
Requirement already satisfied (use --upgrade to upgrade): biopython in /usr/local/lib/python2.7/dist-packages (from Fred2==2.0.0a1)
Requirement already satisfied (use --upgrade to upgrade): svmlight in /usr/local/lib/python2.7/dist-packages (from Fred2==2.0.0a1)
Requirement already satisfied (use --upgrade to upgrade): MySQL-python in /usr/local/lib/python2.7/dist-packages (from Fred2==2.0.0a1)
Downloading/unpacking python-dateutil (from pandas->Fred2==2.0.0a1)
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB): 188kB downloaded
Downloading/unpacking pytz>=2011k (from pandas->Fred2==2.0.0a1)
  Downloading pytz-2015.4-py2.py3-none-any.whl (475kB): 475kB downloaded
Downloading/unpacking numpy>=1.7.0 (from pandas->Fred2==2.0.0a1)
  Downloading numpy-1.9.2.tar.gz (4.0MB): 4.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking PyUtilib==5.1.3556 (from pyomo>=4.0->Fred2==2.0.0a1)
  Downloading PyUtilib-5.1.3556-py2.py3-none-any.whl (223kB): 223kB downloaded
Downloading/unpacking ply (from pyomo>=4.0->Fred2==2.0.0a1)
  Downloading ply-3.6.tar.gz (281kB): 281kB downloaded
  Running setup.py (path:/tmp/pip_build_root/ply/setup.py) egg_info for package ply
    
Downloading/unpacking nose (from pyomo>=4.0->Fred2==2.0.0a1)
  Downloading nose-1.3.7-py2-none-any.whl (154kB): 154kB downloaded
Downloading/unpacking six>=1.6.1 (from pyomo>=4.0->Fred2==2.0.0a1)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: Fred2, python-dateutil, pytz, numpy, PyUtilib, ply, nose, six
  Running setup.py install for Fred2
    error: can't copy 'Fred2/Data/svms': doesn't exist or not a regular file
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-W433WE-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LNNf6d-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/Fred2

copying Fred2/__init__.py -> build/lib.linux-x86_64-2.7/Fred2

creating build/lib.linux-x86_64-2.7/Fred2/EpitopePrediction

copying Fred2/EpitopePrediction/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopePrediction

copying Fred2/EpitopePrediction/External.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopePrediction

copying Fred2/EpitopePrediction/PSSM.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopePrediction

copying Fred2/EpitopePrediction/SVM.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopePrediction

creating build/lib.linux-x86_64-2.7/Fred2/EpitopeSelection

copying Fred2/EpitopeSelection/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopeSelection

copying Fred2/EpitopeSelection/OptiTope.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopeSelection

creating build/lib.linux-x86_64-2.7/Fred2/HLAtyping

copying Fred2/HLAtyping/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/HLAtyping

copying Fred2/HLAtyping/HLAtyping.py -> build/lib.linux-x86_64-2.7/Fred2/HLAtyping

creating build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/EnsemblAdapter.py -> build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/FileReader.py -> build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/RefSeqAdapter.py -> build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/UniProtAdapter.py -> build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/MartsAdapter.py -> build/lib.linux-x86_64-2.7/Fred2/IO

copying Fred2/IO/ADBAdapter.py -> build/lib.linux-x86_64-2.7/Fred2/IO

creating build/lib.linux-x86_64-2.7/Fred2/EpitopeAssembly

copying Fred2/EpitopeAssembly/EpitopeAssembly.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopeAssembly

copying Fred2/EpitopeAssembly/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopeAssembly

copying Fred2/EpitopeAssembly/MosaicVaccine.py -> build/lib.linux-x86_64-2.7/Fred2/EpitopeAssembly

creating build/lib.linux-x86_64-2.7/Fred2/Distance2Self

copying Fred2/Distance2Self/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Distance2Self

copying Fred2/Distance2Self/Distance2Self.py -> build/lib.linux-x86_64-2.7/Fred2/Distance2Self

copying Fred2/Distance2Self/DistanceMatrix.py -> build/lib.linux-x86_64-2.7/Fred2/Distance2Self

creating build/lib.linux-x86_64-2.7/Fred2/Apps

copying Fred2/Apps/SNEPv3.py -> build/lib.linux-x86_64-2.7/Fred2/Apps

copying Fred2/Apps/EpitopeAssembly.py -> build/lib.linux-x86_64-2.7/Fred2/Apps

copying Fred2/Apps/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Apps

copying Fred2/Apps/EpitopePrediction.py -> build/lib.linux-x86_64-2.7/Fred2/Apps

copying Fred2/Apps/SpacerDesign.py -> build/lib.linux-x86_64-2.7/Fred2/Apps

creating build/lib.linux-x86_64-2.7/Fred2/TAPPrediction

copying Fred2/TAPPrediction/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/TAPPrediction

copying Fred2/TAPPrediction/PSSM.py -> build/lib.linux-x86_64-2.7/Fred2/TAPPrediction

copying Fred2/TAPPrediction/SVM.py -> build/lib.linux-x86_64-2.7/Fred2/TAPPrediction

creating build/lib.linux-x86_64-2.7/Fred2/Data

copying Fred2/Data/EpitopePSSMMatrices.py -> build/lib.linux-x86_64-2.7/Fred2/Data

copying Fred2/Data/CleaveagePSSMMatrices.py -> build/lib.linux-x86_64-2.7/Fred2/Data

copying Fred2/Data/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data

copying Fred2/Data/DistanceMatrices.py -> build/lib.linux-x86_64-2.7/Fred2/Data

copying Fred2/Data/TAPPSSMMatrices.py -> build/lib.linux-x86_64-2.7/Fred2/Data

copying Fred2/Data/UniTope_encodedAlleles.py -> build/lib.linux-x86_64-2.7/Fred2/Data

creating build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/DummyAdapter.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/EpitopePredictionTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/ProteinTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/DummyEpitopePredictor.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/EpitopeAssemblyTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/SpacerDesignTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/OptiTopeTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/CleavagePredictionTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/test_transcript_generator.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/TAPPredictionTest.py -> build/lib.linux-x86_64-2.7/Fred2/test

copying Fred2/test/VariantsForTesting.py -> build/lib.linux-x86_64-2.7/Fred2/test

creating build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Result.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Allele.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Base.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Protein.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Peptide.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Transcript.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Variant.py -> build/lib.linux-x86_64-2.7/Fred2/Core

copying Fred2/Core/Generator.py -> build/lib.linux-x86_64-2.7/Fred2/Core

creating build/lib.linux-x86_64-2.7/Fred2/CleavagePrediction

copying Fred2/CleavagePrediction/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/CleavagePrediction

copying Fred2/CleavagePrediction/ANN.py -> build/lib.linux-x86_64-2.7/Fred2/CleavagePrediction

copying Fred2/CleavagePrediction/PSSM.py -> build/lib.linux-x86_64-2.7/Fred2/CleavagePrediction

creating build/lib.linux-x86_64-2.7/Fred2/Data/svms

copying Fred2/Data/svms/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data/svms

creating build/lib.linux-x86_64-2.7/Fred2/Data/svms/svmtap

copying Fred2/Data/svms/svmtap/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data/svms/svmtap

creating build/lib.linux-x86_64-2.7/Fred2/Data/svms/MHCIIMulti

copying Fred2/Data/svms/MHCIIMulti/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data/svms/MHCIIMulti

creating build/lib.linux-x86_64-2.7/Fred2/Data/svms/unitope

copying Fred2/Data/svms/unitope/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data/svms/unitope

creating build/lib.linux-x86_64-2.7/Fred2/Data/svms/svmhc

copying Fred2/Data/svms/svmhc/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data/svms/svmhc

creating build/lib.linux-x86_64-2.7/Fred2/Data/svms/MHCIIMulti/models

copying Fred2/Data/svms/MHCIIMulti/models/__init__.py -> build/lib.linux-x86_64-2.7/Fred2/Data/svms/MHCIIMulti/models

error: can't copy 'Fred2/Data/svms': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-W433WE-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LNNf6d-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-W433WE-build
Storing debug log for failure in /root/.pip/pip.log

**Comment by b-schubert** [comment]
the described installation errors are now fixed. Thanks.
