### ISSUE TITLE
netMHCpan-3.0 removed * from Allele representation

### ISSUE THREAD

**Issue by horse90** [FRED-2/Fred2#164]
so calling 
```
pred = EpitopePredictorFactory("netmhcpan", version='3.0')
pred.predict([Peptide('SYFPEITHI'), Peptide('FIASNGVKL')], Allele("HLA-A*02:01"), command='/usr/bin/netMHCpan')
```

won't return a result, whereas
```
pred = EpitopePredictorFactory("netmhcpan", version='3.0')
pred.predict([Peptide('SYFPEITHI'), Peptide('FIASNGVKL')], Allele("HLA-A02:01"), command='/usr/bin/netMHCpan')
```
won't work because of the Allele representation in the Fred2 package.

When I call netMHCpan outside of python, this works:
`netMHCpan -p test.pep -a 'HLA-A02:01'`
whereas this throws an error (`No match.`)
`netMHCpan -p test.pep -a 'HLA-A*02:01'`

**Comment by b-schubert** [comment]
Unfortunately, I cannot reproduce the error. 

Could you please verify that you are indeed using NetMHCpan 3.0 and have the latest version of the FRED's Master-Branch. The output format of NetMHCpan 3.0 and older version differ which could cause this error.

Which operating system are you using? Linux or OS X?

**Comment by horse90** [comment]
Thanks for the quick reply!
So my examples above all work fine on your system?

I upgraded Fred2 today (`pip install --upgrade git+https://github.com/FRED-2/Fred2`).
It is running on a Linux Mint system, in a virtualenv. Also, i have NetMHCpan 3.0, it was installed some days ago and is working fine.
