### ISSUE TITLE
Codon SEQ is invalid

### ISSUE THREAD

**Issue by Leon-Bichmann** [FRED-2/Fred2#188]
Translating variants into proteins results in the following error during transcription:

```
variants=Fred2.IO.FileReader.read_vcf("my.ann.vcf")

ma=MartsAdapter(biomart="http://ensembl.org")
ID_SYSTEM_USED=EIdentifierTypes.ENSEMBL

try:
    #generate transcripts containing variants, filter for unmutated sequences
    transcripts = generate_transcripts_from_variants([variants[0][0]], ma, ID_SYSTEM_USED)

    #generate proteins from transcripts, table='Standard', stop_symbol='*', to_stop=True, cds=False
    proteins = generate_proteins_from_transcripts(transcripts)
    
except:
    pass
```

 
/Library/anaconda/lib/python2.7/site-packages/Fred2/Core/Generator.py:363: UserWarning: Intersecting variants found for Transcript ENST00000359836
  warnings.warn("Intersecting variants found for Transcript %s"%tId)
Traceback (most recent call last):
  File "ProteoVariants.py", line 415, in <module>
    __main__()
  File "ProteoVariants.py", line 227, in __main__
    proteins = [x for x in protein_gen if x.vars]  # removing unvaried
  File "/Library/anaconda/lib/python2.7/site-packages/Fred2/Core/Generator.py", line 414, in generate_proteins_from_transcripts
    prot_seq = str(t.translate(table=table, stop_symbol=stop_symbol, to_stop=to_stop, cds=cds))
  File "/Library/anaconda/lib/python2.7/site-packages/Bio/Seq.py", line 1025, in translate
    cds, gap=gap)
  File "/Library/anaconda/lib/python2.7/site-packages/Bio/Seq.py", line 2098, in _translate_str
    "Codon '{0}' is invalid".format(codon))
Bio.Data.CodonTable.TranslationError: Codon 'SEQ' is invalid

**Comment by Leon-Bichmann** [comment]
Turns out I was using variants referring to the old version GRCH38.78 that probably have been updated. Resulting into wrong references with transcripts equal to the string:

"SEQUENCE UNKNOWN"

**Comment by b-schubert** [comment]
So, can I close the issue then?
