### ISSUE TITLE
Distance2Self

### ISSUE THREAD

**Issue by monikasekelja** [FRED-2/Fred2#207]
When are you planning to implement Distance2Self method?

**Comment by b-schubert** [comment]
We actually have a working example in another repository; see here: 

https://github.com/APERIM-EU/WP3-Distance2Self

But you have to compile some C-code for it to work (code is in ```src``` and requires some boost libraries), or use the corresponding Docker container.
We were planning on migrating the code into Fred2 but haven't found the time yet.

**Comment by monikasekelja** [comment]
Yes, I found it and installed via docker. Thanks! I hope it will be implemented in Fred2 soon :-)

**Comment by b-schubert** [comment]
You might also be interested in these pre-calculated human proteome Tries of different k-mer length:

https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l8.trie
https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l9.trie
https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l10.trie
https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l11.trie

**Comment by monikasekelja** [comment]
Hi again, Benjamin,

The "distance-to-self" calculations explained in Dr. Feldhahn in chapter 5
are based on the differences between WT and MT peptide measured by
BLOSUM50. And a check is performed, not to the complete human proteome, but
only to the thymus-min proteome to which T cells were trained against. But
what about the idea of T-cells being able to only see a small part of the
peptide bound to the MHC molecule? And that this part is probably trained
against the whole human proteome, even also to the proteome from human
microbiome? This idea was presented in He, Lu et al. 2014 and Moise
Leonard, et al 2013:
- http://www.tandfonline.com/doi/full/10.4161/hv.24615
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4094998/

Is this something you are planning to implement in Fred2? Are you still
working on further development and improvements of this framework or have
you changed research field of interest? (I see that you are now in US in
another research group)...

Sorry for so many questions... I think you have done a tremendous job with
Fred2 and it would be really pity if you stop further improvements.


Greetings from
 - Monika


2017-08-05 17:14 GMT+02:00 b-schubert <notifications@github.com>:

**Comment by monikasekelja** [comment]
Hi Benjamin,
Do you have any precalculated tries for mouse proteome? I have the proteome, but I am not sure how to calculate the trie correctly. 
By the way, are you coming to Neoantigen Summit in November in Boston? It would be nice to meet and discuss this in a coffee break :-)
- Monika


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: b-schubert <notifications@github.com> Date: 8/5/17  17:14  (GMT+01:00) To: FRED-2/Fred2 <Fred2@noreply.github.com> Cc: monikasekelja <monikasekelja@gmail.com>, Author <author@noreply.github.com> Subject: Re: [FRED-2/Fred2] Distance2Self (#207) 
You might also be interested in these pre-calculated human proteome Tries of different k-mer length:
https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l8.trie

https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l9.trie

https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l10.trie

https://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l11.trie

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FRED-2/Fred2","title":"FRED-2/Fred2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FRED-2/Fred2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@b-schubert in #207: You might also be interested in these pre-calculated human proteome Tries of different k-mer length:\r\n\r\nhttps://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l8.trie\r\nhttps://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l9.trie\r\nhttps://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l10.trie\r\nhttps://netcologne.dl.sourceforge.net/project/immunonode-files/uniprot_proteome_l11.trie\r\n"}],"action":{"name":"View Issue","url":"https://github.com/FRED-2/Fred2/issues/207#issuecomment-320449156"}}}
