### ISSUE TITLE
List dependencies explicitly

### ISSUE THREAD

**Issue by apeltzer** [FRED-2/Fred2#213]
Could you list dependencies of the script more explicitly? e.g. in the readme? 

Searching the `setup.py` is not quite nice ;-)

**Comment by b-schubert** [comment]
What's the reason for needing an explicit list of python dependencies? They are automatically resolved during installation anyways... 

I agree with you insofar that we should list the external dependencies that we can't ship with the package due to licensing issues.

**Comment by apeltzer** [comment]
External installation tools such as conda  (e.g. see here https://github.com/bioconda/bioconda-recipes/pull/11469 ) typically require to install the dependencies via extra bioconda packages and not via pip. That also allows pinning specific python versions in order to make sure that things don't break, especially if multiple tools are installed in a single conda environment.

**Comment by b-schubert** [comment]
resolved in PR #219
