### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by apeltzer** [FRED-2/Fred2#214]
You could add this to your readme for users to install the package:

[![Anaconda-Server Badge](https://anaconda.org/bioconda/fred2/badges/installer/conda.svg)](https://conda.anaconda.org/bioconda)

**Comment by b-schubert** [comment]
Sure thing. Will do it on the weekend. Could you intern change the description of the Conda package? It is not really informative.

Perhaps to something like this: "Immunoinformatics library covering (neo)epitope prediction, antigen processing, HLA genotyping, and vaccine design"

**Comment by apeltzer** [comment]
Already took your headline from the repository and updated it - its building on biocondas servers now!

**Comment by b-schubert** [comment]
Great thanks for your help!

**Comment by apeltzer** [comment]
You're welcome - we're using it and making it installable via bioconda was the way to go :-)

**Comment by b-schubert** [comment]
resolved in PR #216
