### ISSUE TITLE
Support for modern epitope prediction tools

### ISSUE THREAD

**Issue by Zethson** [FRED-2/Fred2#224]
Hi,

I am planning on using immunonode's neoepitope script for [mhcquant](https://github.com/nf-core/mhcquant). However, the currently implemented epitope prediction tools don't support enough lengths and alleles for my needs.
 
Are there any plans of integrating [MHCFlurry](https://github.com/openvax/mhcflurry) or [MHCNuggets](https://github.com/KarchinLab/mhcnuggets-2.0) into FRED 2?

@christopher-mohr did you already work on this?

Thanks.

**Comment by christopher-mohr** [comment]
Hey, so far I didn't start to work on this but it would definitely be nice to have support for these methods in FRED2. Right now I can't give you a timeline for this. Feel free to start... ;)

**Comment by Zethson** [comment]
I'm almost done with this. Will open PR tomorrow.
