### ISSUE TITLE
NetMHC(AExternalEpitopePrediction) cannot work

### ISSUE THREAD

**Issue by mwalzer** [FRED-2/Fred2#24]
documented to be designed for netMHC-3.0, which needs the alleles in the form type locussupertypesubtype, but gives it in form HLA-locussupertypesubtype (https://github.com/FRED-2/Fred2/blob/master/Fred2/EpitopePrediction/External.py#L144)

**Comment by mwalzer** [comment]
which is how netMHC-3.4 expects the alleles

**Comment by b-schubert** [comment]
the comment might be an old relic.But this raises the question, if and how we should support older versions.

I would say for the initial publication, we should stick with the newest versions and ones these are been updated we can think about a nice way to model this version dependencies.

**Comment by b-schubert** [comment]
Solve by new versioning system.
