### ISSUE TITLE
netMHC.parse_external_result numerically changes the scores and adds an 'Average' score over the predicted alleles

### ISSUE THREAD

**Issue by mwalzer** [FRED-2/Fred2#25]
NetMHC version 3.0. 9mer predictions using Artificial Neural Networks. Allele B1501. 
Strong binder threshold  50 nM. Weak binder threshold score 500 nM

----------------------------------------------------------------------------------------------------
 pos    peptide      logscore affinity(nM) Bind Level    Protein Name  Allele
----------------------------------------------------------------------------------------------------
   0  SYFPEITHI         0.035        34396                   Peptides   B1501
--------------------------------------------------------------------------------------------------

NetMHC version 3.0. 9mer predictions using Artificial Neural Networks. Allele A0201. 
Strong binder threshold  50 nM. Weak binder threshold score 500 nM

----------------------------------------------------------------------------------------------------
 pos    peptide      logscore affinity(nM) Bind Level    Protein Name  Allele
----------------------------------------------------------------------------------------------------
   0  SYFPEITHI         0.100        17015                   Peptides   A0201
--------------------------------------------------------------------------------------------------

dis
{'Average': defaultdict(None, {'SYFPEITHI': 1.2083032451849778}), 'B1501': defaultdict(None, {'SYFPEITHI': 0.03457397342591528}), 'A0201': defaultdict(None, {'SYFPEITHI': 0.09962567338634032})}

**Comment by b-schubert** [comment]
I think the numerical instability is introduced by 

````
            
for ic_50, a in itertools.izip(l[3:],alleles):
                sc = 1.0 - math.log(float(ic_50), 50000)
                result[a][pep_seq] = sc if sc > 0.0 else 0.0
```

This snipet is probably a relict from earlyer versions. I'm not quit sure why we recalculate the transformed IC50 value and not just take the one from the NetMHC output.

**Comment by mwalzer** [comment]
okay, so average is only added by netMHC-3.0

**Comment by b-schubert** [comment]
partly solved by new versioning system.

**Comment by b-schubert** [comment]
close?
