### ISSUE TITLE
generate_proteins_from_transcripts is registering the variants at the transcript position

### ISSUE THREAD

**Issue by mwalzer** [FRED-2/Fred2#52]

**Comment by b-schubert** [comment]
? it doesn't 

The function calulates the protein position with:

`int(math.ceil(pos/3.0))` 

`prot_pos = pos / 3`  seems to do the same implicitly.

Seq

**Comment by b-schubert** [comment]
`prot_pos = pos / 3`

should be changed to:

`prot_pos = pos // 3`

according to [PEP238](https://www.python.org/dev/peps/pep-0238/)

**Comment by mwalzer** [comment]
so the problem with ```int(math.ceil(pos/3.0))``` is that if our positions are 0 based -which they should- prot_pos is wrong.

**Comment by mwalzer** [comment]
totally agree on following [PEP238](https://www.python.org/dev/peps/pep-0238/)

**Comment by b-schubert** [comment]
resolved with PR #54
