### ISSUE TITLE
HLA Typing

### ISSUE THREAD

**Issue by b-schubert** [FRED-2/Fred2#8]
Should we also integrate wrapper function to prominent HLA typing methods?

Which one should those be besides OptiType?:

- seq2HLA
- Athlates
- HLAminer
- HLAforrest

**Comment by mwalzer** [comment]
@christopher-mohr @ andras86
Which ones should we include? Who wants to do it?

**Comment by b-schubert** [comment]
started implementing wrappers:

Done:
- seq2HLA
- Athlates
- Optitype

To come:
- HLAminer

Due to the fact that each tool returns the genotype differently, I'm only returning the inferred HLA-Alleles nothing more.
